<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="Hauptprogramme" Id="{69666071-2ef3-4bfb-9e05-1198fc076d6e}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM Hauptprogramme
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="Hauptprogramme">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>