<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.12">
  <POU Name="PRG_MainControl" Id="{7e1b5104-3b2d-4a57-a4a2-4a95db04a8c6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_MainControl
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[p_Burning();
p_Delivering();
p_Sawing();
p_ColorSorting();
p_Retrieving();
p_Picking();
p_Placing();
p_Storing();
// p_Punching();]]></ST>
    </Implementation>
    <LineIds Name="PRG_MainControl">
      <LineId Id="227" Count="7" />
      <LineId Id="38" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>
